### PR TITLE
Disregard case when resolving file name conflicts

### PR DESCRIPTION
**Pull request by Vampire**

### CODE REVIEW

**Comment by Vampire** [comment]
Oh, are they? :-(
Here they were green.
Well, with my change in the tests they were red and with my code change they became green.

**Comment by Vampire** [comment]
Ah, on Windows the run would have been successful, but was canceled.
Due to the change the file name changed from `MyClass.kt` to `myClass.kt` but Windows did not properly record that of course, sorry.

**Comment by sgrishchenko** [comment]
I checked this case. I throw this error on purpose because file names in macOS are case-insensitive. So in macOS `myClass.kt` function file will override `MyClass.kt` class file (or vise verse, depends on conversion order). I will close it, ok?

сс @turansky

**Comment by sgrishchenko** [comment]
And there is another issue, now `MyClass` class is placed in `myClass` file, which looks a bit odd to me.

**Comment by Vampire** [comment]
> I will close it, ok?

No, not ok, as you still don't get it it seems. :-)

I'm on Windows, there you have the same problem.

And the problem is, that you then cannot convert due to that conflict.

This PR does not disable the warning and makes the files overwrite each other.

This PR makes both files be merged into one, thus properly handling this conflict instead of throwing an error, as long as the files can be merged (module / qualifier).

> And there is another issue, now MyClass class is placed in myClass.kt file, which looks a bit odd to me.

The point is, that you get `myClass` function and `MyClass` class now both in the same file.
So either you have `myClass` in `MyClass.kt` or `MyClass` in `myClass.kt`, whatever filename came first.
Neither is more correct than the other, but at least you get both files content merged instead of a conflict error.

**Comment by turansky** [comment]
> The point is, that you get myClass function and MyClass class now both in the same file.

I expect 2 separate files instead

**Comment by Vampire** [comment]
Named how and with which tactic?
You cannot name them `myClass.kt` and `MyClass.kt`, that is currently the case and is then explicitly forbidden as that only works on case-sensitive filesystems.

**Comment by sgrishchenko** [comment]
I use this approach in node declaration: if I have conflicts in file names, use a simple name for the primary entity and add suffixes with an entity type for the rest. What is the primary entity? Good question, I use this priority list:
* class 
* function 
* enum
* interface
* namespace

So If I have this declaration
```ts
class MyClass {} 
function myClass() {}
```
I will produce this files
* `MyClass.kt` for class
* `myClass.fun.kt` for function

This algorithm is manual, but we can try to automate during conflict resolution.
Example from Wrappers
* kotlin-node/src/jsMain/generated/node/crypto/DiffieHellman.kt
* kotlin-node/src/jsMain/generated/node/crypto/diffieHellman.fun.kt
* Karakum config:
  ```json
       "packageNameMapper": {
           "^crypto/diffieHellman.kt": "node/crypto/diffieHellman.fun.kt", 
       }
  ```

**Comment by sgrishchenko** [comment]
It seems the root issue here is that with fine-grained TS declarations + top-level strategy you will have lots of problems: for each declaration you will have conflict: original file name vs declared entity inside. @Vampire Is my guess correct?

**Comment by Vampire** [comment]
> if I have conflicts in file names, use a simple name for the primary entity and add suffixes with an entity type for the rest

Ah, I see, thanks.
With different casing `packagNameMapper` can be used of course.

> This algorithm is manual, but we can try to automate during conflict resolution.

That would maybe be good, especially for potential other Karakum users.

> Is my guess correct?

Here the ones for Ajv, not that many

Files have the same name but different casing:
D:\Sourcecode\other\kotlin-wrappers\kotlin-ajv\src\jsMain\generated\ajv\ajv.kt
D:\Sourcecode\other\kotlin-wrappers\kotlin-ajv\src\jsMain\generated\ajv\Ajv.kt
Files have the same name but different casing:
D:\Sourcecode\other\kotlin-wrappers\kotlin-ajv\src\jsMain\generated\ajv\compile\codegen\code.kt
D:\Sourcecode\other\kotlin-wrappers\kotlin-ajv\src\jsMain\generated\ajv\compile\codegen\Code.kt
Files have the same name but different casing:
D:\Sourcecode\other\kotlin-wrappers\kotlin-ajv\src\jsMain\generated\ajv\compile\codegen\scope.kt
D:\Sourcecode\other\kotlin-wrappers\kotlin-ajv\src\jsMain\generated\ajv\compile\codegen\Scope.kt
Files have the same name but different casing:
D:\Sourcecode\other\kotlin-wrappers\kotlin-ajv\src\jsMain\generated\ajv\compile\validate\dataType.kt
D:\Sourcecode\other\kotlin-wrappers\kotlin-ajv\src\jsMain\generated\ajv\compile\validate\DataType.kt
Files have the same name but different casing:
D:\Sourcecode\other\kotlin-wrappers\kotlin-ajv\src\jsMain\generated\ajv\runtime\validationError.kt
D:\Sourcecode\other\kotlin-wrappers\kotlin-ajv\src\jsMain\generated\ajv\runtime\ValidationError.kt
Files have the same name but different casing:
D:\Sourcecode\other\kotlin-wrappers\kotlin-ajv\src\jsMain\generated\ajv\runtime\uri.kt
D:\Sourcecode\other\kotlin-wrappers\kotlin-ajv\src\jsMain\generated\ajv\runtime\URI.kt
Files have the same name but different casing:
D:\Sourcecode\other\kotlin-wrappers\kotlin-ajv\src\jsMain\generated\ajv\runtime\re2.kt
D:\Sourcecode\other\kotlin-wrappers\kotlin-ajv\src\jsMain\generated\ajv\runtime\Re2.kt
Files have the same name but different casing:
D:\Sourcecode\other\kotlin-wrappers\kotlin-ajv\src\jsMain\generated\ajv\runtime\equal.kt
D:\Sourcecode\other\kotlin-wrappers\kotlin-ajv\src\jsMain\generated\ajv\runtime\Equal.kt

And actually in those lower-case files there is no declaration with that lowercase name but other things that just were in that lower-case `.d.ts` file.

**Comment by Vampire** [comment]
```plain
$ find kotlin-ajv/src/jsMain/generated/ -name '*lower*' -exec sh -c 'echo; echo {}; cat {}' \;

kotlin-ajv/src/jsMain/generated/ajv/compile/codegen/code.lower.kt
// Generated by Karakum - do not modify it manually!

@file:JsModule("ajv/compile/codegen/code")

package ajv.compile.codegen

external val IDENTIFIER: RegExp

external val nil: _Code

// export {};

kotlin-ajv/src/jsMain/generated/ajv/compile/codegen/scope.lower.kt
// Generated by Karakum - do not modify it manually!

@file:JsModule("ajv/compile/codegen/scope")

package ajv.compile.codegen

// unhandled import: Code from "./code"
// unhandled import: Name from "./code"

external val varKinds: VarKinds

// export {};

kotlin-ajv/src/jsMain/generated/ajv/compile/validate/dataType.lower.kt
// Generated by Karakum - do not modify it manually!

@file:JsModule("ajv/compile/validate/dataType")

package ajv.compile.validate

// unhandled import: ErrorObject from "../../types"
// unhandled import: AnySchemaObject from "../../types"
// unhandled import: SchemaObjCxt from ".."
// unhandled import: JSONType from "../rules"
// unhandled import: Code from "../codegen"
// unhandled import: Name from "../codegen"

kotlin-ajv/src/jsMain/generated/ajv/runtime/equal.lower.kt
// Generated by Karakum - do not modify it manually!

@file:JsModule("ajv/runtime/equal")

package ajv.runtime

// unhandled import: * as equal from "fast-deep-equal"

external val _default: Equal

// export default _default;

kotlin-ajv/src/jsMain/generated/ajv/runtime/re2.lower.kt
// Generated by Karakum - do not modify it manually!

@file:JsModule("ajv/runtime/re2")

package ajv.runtime

// unhandled import: * as re2 from "re2"

external val _default: Re2

// export default _default;

kotlin-ajv/src/jsMain/generated/ajv/runtime/uri.lower.kt
// Generated by Karakum - do not modify it manually!

@file:JsModule("ajv/runtime/uri")

package ajv.runtime

// unhandled import: * as uri from "fast-uri"

external val _default: URI

// export default _default;

kotlin-ajv/src/jsMain/generated/ajv/runtime/validationError.lower.kt
// Generated by Karakum - do not modify it manually!

@file:JsModule("ajv/runtime/validation_error")

package ajv.runtime

// unhandled import: ErrorObject from "../types"
```

**Pull request closed without merging**
